apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-dep-v2
  labels:
    app: udacityp5-lables
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacityp5-lables
  template:
    metadata:
      labels:
        app: udacityp5-lables
    spec:
      containers:
      - name: udacityp5
        image: caskeep/udacityp5
        ports:
        - containerPort: 8000